FORMAT: 1A
HOST: https://aws-vs002.inps.co.uk

# VHG_demo


# Group Appointments

## Appointments V11 Organisations Patients 4 Notes [/appointments/v1.1/organisations//patients/4/notes]

### Appt  Get Pat Notes copy [GET]

+ Request (application/json)
    + Headers

            X-Business-TransactionId:9ee5e257-b2a2-41cc-83f6-d4d397aa3ac3
            Accept-Encoding:gzip
            Authorization:vision_connection token=





+ Response 200 





# Group MPI

## V1 MasterPatientIndex PatientViews [/v1/masterPatientIndex/patientViews]

### Master Patient Search copy [POST]
Post a set filter criteria to the "patientViews" collection and return display details for the matching patients. Filter criteria can be partial.
## Supported ID systems are;
* NHS
* CHI

+ Request (application/json)
    + Headers

            X-Business-TransactionId:6f0872e6-09b4-4f97-8557-7553a5e6ec0b
            Accept-Encoding:gzip
            Authorization:vision_connection token=


    + Attributes (Master Patient Search copy Request)


    + Body

            {
                "identifier": {
                    "system": "http://fhir.nhs.net/Id/nhs-number",
                    "value": "{{nhs_no}}"
                },
                "dob": "1996-07-05",
                "forenamePart": "JOHN",
                "surnamePart": "KENNEDY",
                "postcodePart": "{{patient_postcode}}",
                "address": "{{patient_address}}"
            }


+ Response 200 





# Group Misc

## V2 Session Connections [/v2/session_connections]

### Security  Login copy [POST]
Get session connections

+ Request (application/json)
    + Headers

            X-Business-TransactionId:9667281b-3222-461b-97a3-e8005eeb00f2
            Accept-Encoding:gzip


    + Attributes (Security  Login copy Request)


    + Body

            {
                "auth_type": "password",
                "user_name": "fiona.venus@inps.net",
                "secret": "password1",
                "role_id": "",
                "client": {
                    "device_id": "{{device_id}}",
                    "product_key": "{{product_key}}",
                    "product_version": "{{product_version}}",
                    "other_details": "Tony testing 1644359904"
                }
            }


+ Response 200 




## V1 Organisations Patients 4 [/v1/organisations//patients/4]

### Patient  Get Patients by ID copy [GET]

+ Request (application/json)
    + Headers

            X-Business-TransactionId:b67e65a2-fb5a-4c60-9710-5e231708ed03
            accept-encoding:gzip, deflate
            Authorization:vision_connection token=





+ Response 200 




## V1 Organisations CareRecords [/v1/organisations//careRecords]

### Request patient record copy [POST]
Get care records
Pass in patient id and DoB.

+ Request (application/json)
    + Headers

            X-Business-TransactionId:b45a28ee-634a-40b8-a8f1-56248a238eeb
            Accept-Encoding:gzip
            Authorization:vision_connection token=


    + Attributes (Request patient record copy Request)


    + Body

            {
                "patient": {
                    "id": "4",
                    "dob": "1996-07-05"
                },
                "filter": {}
            }


+ Response 200 



### Write chronic back pain [PATCH]
First write back

+ Request (application/json)
    + Headers

            X-Business-TransactionId:ab6d22e8-2cb6-472c-be89-3cbfb3df4224
            Accept-Encoding:gzip
            Authorization:vision_connection token=


    + Attributes (Write chronic back pain Request)


    + Body

            {
                "patient": [
                    {
                        "id": "4",
                        "dob": "1996-07-05",
                        "consultation": [
                            {
                                "eventdate": "2017-03-22",
                                "master_id": "4",
                                "category": {
                                    "coding": [
                                        {
                                            "system": "http://visionhealth.co.uk/picklist",
                                            "code": "COT009",
                                            "display": "Surgery consultation"
                                        }
                                    ]
                                },
                                "items": [
                                    {
                                        "codedEntry": {
                                            "eventdate": "2017-03-22",
                                            "master_id": "4",
                                            "topic": 1,
                                            "code": {
                                                "coding": [
                                                    {
                                                        "system": "http://read.info/readv2",
                                                        "code": "16C9.00",
                                                        "display": "Chronic low back pain"
                                                    }
                                                ]
                                            },
                                            "notes": "TT and max 1644359904"
                                        }
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }


+ Response 200 





# Data Structures

## Master Patient Search copy Request (object)


### Properties
+ `identifier` (Identifier, required) 
+ `dob` (string, required) 
+ `forenamePart` (string, required) 
+ `surnamePart` (string, required) 
+ `postcodePart` (string, required) 
+ `address` (string, required) 


## Identifier (object)


### Properties
+ `system` (string, required) 
+ `value` (string, required) 


## Security  Login copy Request (object)


### Properties
+ `auth_type` (string, required) 
+ `user_name` (string, required) 
+ `secret` (string, required) 
+ `role_id` (string, required) 
+ `client` (Client, required) 


## Client (object)


### Properties
+ `device_id` (string, required) 
+ `product_key` (string, required) 
+ `product_version` (string, required) 
+ `other_details` (string, required) 


## Request patient record copy Request (object)


### Properties
+ `patient` (Patient, required) 
+ `filter` (object, required) 


## Patient (object)


### Properties
+ `id` (string, required) 
+ `dob` (string, required) 


## Write chronic back pain Request (object)


### Properties
+ `patient` (array[Patient1], required) 


## Patient1 (object)


### Properties
+ `id` (string, required) 
+ `dob` (string, required) 
+ `consultation` (array[Consultation], required) 


## Consultation (object)


### Properties
+ `eventdate` (string, required) 
+ `master_id` (string, required) 
+ `category` (Category, required) 
+ `items` (array[Item], required) 


## Category (object)


### Properties
+ `coding` (array[Coding], required) 


## Coding (object)


### Properties
+ `system` (string, required) 
+ `code` (string, required) 
+ `display` (string, required) 


## Item (object)


### Properties
+ `codedEntry` (CodedEntry, required) 


## CodedEntry (object)


### Properties
+ `eventdate` (string, required) 
+ `master_id` (string, required) 
+ `topic` (number, required) 
+ `code` (Code, required) 
+ `notes` (string, required) 


## Code (object)


### Properties
+ `coding` (array[Coding], required) 

