FORMAT: 1A
HOST: https://vs004.inps.co.uk

# VHG_demo
TODO: Add Description

# Group Appointments

## Appointments V11 Organisations 12345 Patients 3 Notes [/appointments/v1.1/organisations/12345/patients/3/notes]

### Appt  Get Pat Notes copy [GET]
TODO: Add Description

+ Request (application/json)
    + Headers

            X-Business-TransactionId:e3b4031a-c568-4553-b30b-d121cb34e488
            Accept-Encoding:gzip
            Authorization:vision_connection token=3:2-2-d1187f51968b4a4fbf972164aebfcfa4-cc93bfb90fc54cc88bb65bd0ebcedc7d




+ Response 200 





# Group MPI

## V1 MasterPatientIndex PatientViews [/v1/masterPatientIndex/patientViews]

### Master Patient Search copy [POST]
TODO: Add Description

+ Request (application/json)
    + Headers

            X-Business-TransactionId:074278fe-5897-4742-bae9-99bf63febd52
            Accept-Encoding:gzip
            Authorization:vision_connection token=3:2-2-d1187f51968b4a4fbf972164aebfcfa4-cc93bfb90fc54cc88bb65bd0ebcedc7d

    + Attributes (Master Patient Search copyRequest)

    + Body

            {
                "identifier": {
                    "system": "http://fhir.nhs.net/Id/nhs-number",
                    "value": "{{nhs_no}}"
                },
                "dob": "1950-11-08",
                "forenamePart": "{{patient_forename}}",
                "surnamePart": "{{patient_surname}}",
                "postcodePart": "{{patient_postcode}}",
                "address": "{{patient_address}}"
            }


+ Response 200 





# Group Misc

## V2 Session Connections [/v2/session_connections]

### Security  Login copy [POST]
TODO: Add Description

+ Request (application/json)
    + Headers

            X-Business-TransactionId:5888e165-ab23-4f06-b010-fcc25ff0e2a1
            Accept-Encoding:gzip

    + Attributes (Security  Login copyRequest)

    + Body

            {
                "auth_type": "password",
                "user_name": "anton.moonstone@nhs.net",
                "secret": "password3",
                "role_id": "884",
                "client": {
                    "device_id": "{{device_id}}",
                    "product_key": "{{product_key}}",
                    "product_version": "{{product_version}}",
                    "other_details": "Tony testing 1495233487"
                }
            }


+ Response 200 




## V1 Organisations 12345 Patients 3 [/v1/organisations/12345/patients/3]

### Patient  Get Patients by ID copy [GET]
TODO: Add Description

+ Request (application/json)
    + Headers

            X-Business-TransactionId:8d207aa2-c794-4a6c-a8c6-92101f3d564c
            accept-encoding:gzip, deflate
            Authorization:vision_connection token=3:2-2-d1187f51968b4a4fbf972164aebfcfa4-cc93bfb90fc54cc88bb65bd0ebcedc7d




+ Response 200 




## V1 Organisations 12345 CareRecords [/v1/organisations/12345/careRecords]

### Request patient record copy [POST]
TODO: Add Description

+ Request (application/json)
    + Headers

            X-Business-TransactionId:103deac1-6210-41c0-961a-420086445551
            Accept-Encoding:gzip
            Authorization:vision_connection token=3:2-2-d1187f51968b4a4fbf972164aebfcfa4-cc93bfb90fc54cc88bb65bd0ebcedc7d

    + Attributes (Request patient record copyRequest)

    + Body

            {
                "patient": {
                    "id": "3",
                    "dob": "1950-11-08"
                },
                "filter": {}
            }


+ Response 200 



### Write chronic back pain [PATCH]
TODO: Add Description

+ Request (application/json)
    + Headers

            X-Business-TransactionId:0b07aee9-9a9a-4e54-b2f0-16bfc8646c5b
            Accept-Encoding:gzip
            Authorization:vision_connection token=3:2-2-d1187f51968b4a4fbf972164aebfcfa4-cc93bfb90fc54cc88bb65bd0ebcedc7d

    + Attributes (Write chronic back painRequest)

    + Body

            {
                "patient": [
                    {
                        "id": "3",
                        "dob": "1950-11-08",
                        "consultation": [
                            {
                                "eventdate": "2017-03-22",
                                "master_id": "3",
                                "category": {
                                    "coding": [
                                        {
                                            "system": "http://visionhealth.co.uk/picklist",
                                            "code": "COT009",
                                            "display": "Surgery consultation"
                                        }
                                    ]
                                },
                                "items": [
                                    {
                                        "codedEntry": {
                                            "eventdate": "2017-03-22",
                                            "master_id": "3",
                                            "topic": 1,
                                            "code": {
                                                "coding": [
                                                    {
                                                        "system": "http://read.info/readv2",
                                                        "code": "16C9.00",
                                                        "display": "Chronic low back pain"
                                                    }
                                                ]
                                            },
                                            "notes": "TT and max 1495233487"
                                        }
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }


+ Response 200 





# Data Structures

## Master Patient Search copyRequest (object)


### Properties
+ `identifier` (Identifier, required) 
+ `dob` (string, required) 
+ `forenamePart` (string, required) 
+ `surnamePart` (string, required) 
+ `postcodePart` (string, required) 
+ `address` (string, required) 


## Identifier (object)


### Properties
+ `system` (string, required) 
+ `value` (string, required) 


## Security  Login copyRequest (object)


### Properties
+ `auth_type` (string, required) 
+ `user_name` (string, required) 
+ `secret` (string, required) 
+ `role_id` (string, required) 
+ `client` (Client, required) 


## Client (object)


### Properties
+ `device_id` (string, required) 
+ `product_key` (string, required) 
+ `product_version` (string, required) 
+ `other_details` (string, required) 


## Request patient record copyRequest (object)


### Properties
+ `patient` (Patient, required) 
+ `filter` (object, required) 


## Patient (object)


### Properties
+ `id` (string, required) 
+ `dob` (string, required) 


## Write chronic back painRequest (object)


### Properties
+ `patient` (array[Patient7], required) 


## Patient7 (object)


### Properties
+ `id` (string, required) 
+ `dob` (string, required) 
+ `consultation` (array[Consultation], required) 


## Consultation (object)


### Properties
+ `eventdate` (string, required) 
+ `master_id` (string, required) 
+ `category` (Category, required) 
+ `items` (array[Item], required) 


## Category (object)


### Properties
+ `coding` (array[Coding], required) 


## Coding (object)


### Properties
+ `system` (string, required) 
+ `code` (string, required) 
+ `display` (string, required) 


## Item (object)


### Properties
+ `codedEntry` (CodedEntry, required) 


## CodedEntry (object)


### Properties
+ `eventdate` (string, required) 
+ `master_id` (string, required) 
+ `topic` (number, required) 
+ `code` (Code, required) 
+ `notes` (string, required) 


## Code (object)


### Properties
+ `coding` (array[Coding], required) 

